sudo: false
language: node_js
node_js:
  - 12
cache: npm
branches:
  only:
    - master # build master branch only
script:
  - hexo generate
comments:
  valine:
      appId: 'EDiQLCtfYJFYtECr3Adwmncl-gzGzoHsz'
      appKey: 'MDXLAYtR8IlmgStY29ElIjge'
      placeholder: 'Just Go Go.'
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GH_TOKEN
  keep-history: true
  on:
    branch: master
  local-dir: public